import {
    CheckSquare,
    GitBranch,
    MessageCircle,
    StickyNote
} from "lucide-react";
export const basicElements = [
    {
        type: "Attachment",
        category: "basic",
        label: "Attachment",
        color: "bg-cyan-400",
        description: "Attachment",
        defaultValid: false,
        defaults: {
            method: "send",
            fileContent: "",
            message: "please upload your file",
            variableName: "",
        },
    },
    {
        type: "Router",
        label: "Router",
        description: "Route workflow based on multiple conditions",
        icon: GitBranch,
        defaultValid: true,
        category: "basic",
        color: "bg-cyan-500",
        defaults: {
            branches: [
                {
                    label: "branch 1",
                    id: `branch-${Date.now()}`,
                    description: "",
                    operatorType: "number",
                    firstOperator: "",
                    secondOperator: "",
                    checkType: "equal",
                },
            ],
            defaultBranch: { label: "Default", description: "" },
            save: false,
            variableName: "",
            loopFromSwitch: false,
            loopFromName: "",
        },
    },
    {
        type: "ChoicePrompt",
        label: "Multiple Choice",
        defaultValid: true,
        description: "Present multiple options for user selection",
        icon: CheckSquare,
        category: "basic",
        color: "bg-pink-500",
        defaults: {
            botSays: "Hello please choose a choice",
            save: false,
            variableName: "",
            choices: [{ label: "Choice 1", id: `choice-${Date.now()}` }],
            loopFromSwitch: false,
            loopFromName: "",
        },
    },
    {
        name: "Message",
        type: "Message",
        color: "bg-emerald-500",
        defaultValid: false,
        category: "basic",
        label: "Message",
        description: "Send messages and notifications",
        icon: MessageCircle,
        defaults: {
            botSays: "",
            advanced: false,
            regex: "",
            errorMessage: "",
            save: false,
            variableName: "",
            loopFromSwitch: false,
            loopFromName: "",
        },
    },
    {
        type: "StickyNote",
        label: "Sticky Note",
        description: "Sticky paper for quick notes and reminders",
        icon: StickyNote,
        category: "basic",
        color: "bg-lime-500",
        defaultValid: true,
        defaults: {
            color: "#bfdbfe",
            content: "",
        },
    },
]