export const modelOptions = [
    { credType: "LiteLLM", value: "liteLLM", label: "LiteLLM", url: "liteLlm/listModels" },
    { credType: "IBMWatsonx", value: "ibm", label: "IBMWatsonx", url: "ibmWatsonx/listModels" },
    { credType: "OpenRouter", value: "openRouter", label: "OpenRouter", url: "openRouter/listModels" },
    { credType: "Cerebras", value: "cerebras", label: "Cerebras", url: "cerebras/listModels" },
    { credType: "Anthropic", value: "anthropic", label: "Anthropic", url: "anthropic/listModels" },
    { credType: "AzureOpenAi", value: "azureOpenAi", label: "Azure" },
    { credType: "OpenAI", value: "openAi", label: "OpenAI", url: "openai/listModels" },
    { credType: "Ollama", value: "ollama", label: "Ollama", url: "ollama/listModels" },
    { credType: "HuggingFace", value: "huggingFace", label: "HuggingFace" },
    { credType: "TogetherAi", value: "togetherAi", label: "TogetherAI", url: "togetherAi/listModels" },
    { credType: "Cohere", value: "cohere", label: "Cohere", url: "cohere/listModels" },
    { credType: "AWSBedrock", value: "awsBedrock", label: "AWSBedrock" },
    { credType: "MistralAi", value: "mistralAi", label: "MistralAI", url: "mistralAi/listModels" },
    { credType: "VertexAi", value: "vertexAi", label: "VertexAI" },
    { credType: "Gemini", value: "googleGenerativeAi", label: "GoogleGenerativeAi", url: "googleGenerativeAi/listModels" },
    { credType: "Groq", value: "groq", label: "Groq", url: "groq/listModels" },
    { credType: "Fireworks", value: "fireworks", label: "Fireworks" },
    { credType: "Nvidia", value: "nvidia", label: "Nvidia", url: "nvidia/listModels" },
];
